name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build Dockerfile and Push to The Hub
      uses: beehivewarrior/docker-hub-builder@v1.0
      with:
        # The username to authenticate with dockerhub
        DOCKERHUB_USERNAME: DOCKERHUB_USERNAME
        # The token to authenticate with dockerhub
        DOCKERHUB_TOKEN: DOCKERHUB_TOKEN
        # The tag of the base image
        BASE_TAG: latest
        # ARG input into Dockerfile for tag
        TAG_NAME: latest
        # Name of image to publish to dockerhub, e.g. 'user/my-image'
        IMAGE_NAME: bomba1990/django-base
